---
- name: Refresh pacman core database and upgrade system
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install BlackArch Custom Environment Packages
  community.general.pacman:
    name:
      - terminator
      - ligolo-ng
      - feroxbuster
      - evil-winrm
      - certipy
    state: present
