---
- name: Unhash source repositories and update apt cache
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
  when: ansible_distribution == "Kali"

- name: Extract Rockyou wordlist natively
  ansible.builtin.command:
    cmd: gunzip /usr/share/wordlists/rockyou.txt.gz
    creates: /usr/share/wordlists/rockyou.txt
  failed_when: false

- name: Install PimpMyKali essential core tooling
  ansible.builtin.apt:
    name:
      - bloodhound
      - bloodyad
      - amass
      - certipy-ad
      - terminator
      - ligolo-ng
    state: present
